/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsTeamSlugRouteImport } from './routes/teams/$teamSlug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugRoute = TeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/history': typeof HistoryRoute
  '/podcast': typeof PodcastRoute
  '/season': typeof SeasonRoute
  '/admin/login': typeof AdminLoginRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/history': typeof HistoryRoute
  '/podcast': typeof PodcastRoute
  '/season': typeof SeasonRoute
  '/admin/login': typeof AdminLoginRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRoute
  '/admin': typeof AdminIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/history': typeof HistoryRoute
  '/podcast': typeof PodcastRoute
  '/season': typeof SeasonRoute
  '/admin/login': typeof AdminLoginRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/history'
    | '/podcast'
    | '/season'
    | '/admin/login'
    | '/teams/$teamSlug'
    | '/admin/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/history'
    | '/podcast'
    | '/season'
    | '/admin/login'
    | '/teams/$teamSlug'
    | '/admin'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/history'
    | '/podcast'
    | '/season'
    | '/admin/login'
    | '/teams/$teamSlug'
    | '/admin/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  HistoryRoute: typeof HistoryRoute
  PodcastRoute: typeof PodcastRoute
  SeasonRoute: typeof SeasonRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TeamsTeamSlugRoute: typeof TeamsTeamSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug': {
      id: '/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof TeamsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  HistoryRoute: HistoryRoute,
  PodcastRoute: PodcastRoute,
  SeasonRoute: SeasonRoute,
  AdminLoginRoute: AdminLoginRoute,
  TeamsTeamSlugRoute: TeamsTeamSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
